apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  template:
    spec:
      containers:
      - name: webserver
        env:
        - name: APP_ENV
          value: "production"
